mod approvals_list;
mod bulk_sales_import;
mod customer_detail;
mod customers_list;
mod dashboard;
mod loan_account_detail;
mod login;
mod new_customer;
mod new_project;
mod not_found;
mod platform_organization_detail;
mod platform_organizations;
mod project_detail;
mod projects_list;
mod quotation_detail;
mod quotations_list;
mod reports;
mod signup;

pub use approvals_list::ApprovalsList;
pub use bulk_sales_import::BulkSalesImport;
pub use customer_detail::CustomerDetail;
pub use customers_list::CustomersList;
pub use dashboard::Dashboard;
pub use loan_account_detail::LoanAccountDetailPage;
pub use login::Login;
pub use new_customer::NewCustomer;
pub use new_project::NewProject;
pub use not_found::NotFound;
pub use platform_organization_detail::PlatformOrganizationDetailPage;
pub use platform_organizations::PlatformOrganizations;
pub use project_detail::ProjectDetail;
pub use projects_list::ProjectsList;
pub use quotation_detail::QuotationDetailPage;
pub use quotations_list::QuotationsList;
pub use reports::Reports;
pub use signup::Signup;
