mod customer_detail;
mod customers_list;
mod dashboard;
mod loan_account_detail;
mod login;
mod new_customer;
mod new_project;
mod not_found;
mod project_detail;
mod projects_list;
mod signup;

pub use customer_detail::CustomerDetail;
pub use customers_list::CustomersList;
pub use dashboard::Dashboard;
pub use loan_account_detail::LoanAccountDetailPage;
pub use login::Login;
pub use new_customer::NewCustomer;
pub use new_project::NewProject;
pub use not_found::NotFound;
pub use project_detail::ProjectDetail;
pub use projects_list::ProjectsList;
pub use signup::Signup;
